sudo: required

services:
  - docker

before_install:
  - docker build -t hunter-thompson/legalist-api -f legalist-api/Dockerfile.dev

script:
  - docker run -e CI=true hunter-thompson/legalist-api
  - bash legalist-api/scripts/test.sh