sudo: required

services:
  - docker

before_install:
  - docker-compose up -d --build

script:
  - bash scripts/test.sh

after_success:
  - docker build -t "$DOCKER_ID"/nginx ./nginx
  - docker build -t "$DOCKER_ID"/postgres ./postgres
  - docker build -t "$DOCKER_ID"/api ./
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push "$DOCKERID"/nginx
  - docker push "$DOCKER_ID"/postgres
  - docker push "$DOCKER_ID"/api

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Api"
  env: "Api-env"
  bucket_name: $AWS_BUCKET_NAME
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key:
    secure: "$AWS_SECRET_KEY" 
  
