sudo: required

services:
  - docker

before_install:
  - docker build -t hunter-thompson/legalist-api -f Dockerfile.dev .

script:
  - docker run -e CI=true hunter-thompson/legalist-api -d
  - bash scripts/test.sh