version: '3'
services:
  database:
    build:
      dockerfile: Dockerfile.dev
      context: ./postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PGPORT=5432
      - PGUSER=hunter
      - PGPASSWORD=helloworld
      - PGDATABASE=api
      - PGHOST=database
    ports:
      - "3000:3000"
volumes:
  dbdata:
    driver: 'local'
 
    